import { readFileSync } from 'node:fs';
import { resourcesPath } from '../paths';

// GENERATED by rig/tools/make_homophone_table.py in the macOS repo, and carried
// across unchanged — do not edit by hand.
//
// Every set of English words that CMUdict says are pronounced identically, with
// stress ignored, restricted to words the system dictionary lists as ordinary
// lowercase English. 1073 sets, 2281 distinct words.
//
// This is the CHECK, not the offer. The model proposes a fix freely and
// `contextProjection` refuses it unless the replacement is in the same set as
// the word that was heard, so the blast radius is "words that sound the same"
// by construction rather than by inspection.
//
// Surname spellings are deliberately absent — laurie/lorry/lori and friends are
// proper nouns, they belong to the vocabulary corrector, and letting a model
// swap between them would rewrite someone's name into a different spelling.
//
// It lives in a data file rather than a source literal for the same reason the
// Swift version used a single multi-line string: a 2,300-entry object literal
// costs real parse time on every launch of a menu-bar app that is meant to be
// invisible.

let rawText: string | null = null;
let groups: Map<string, Set<string>> | null = null;

function resolvePath(): string {
  const candidates = [
    resourcesPath() ? `${resourcesPath()}/data/homophones.txt` : '',
    `${__dirname}/../data/homophones.txt`,
    `${__dirname}/../../data/homophones.txt`,
    `${__dirname}/../../../src/data/homophones.txt`,
    `${process.cwd()}/src/data/homophones.txt`,
    `${process.cwd()}/dist/data/homophones.txt`,
  ].filter((path) => path.length > 0);
  for (const path of candidates) {
    try {
      readFileSync(path);
      return path;
    } catch {
      continue;
    }
  }
  throw new Error(`no homophone table found; looked in ${candidates.join(', ')}`);
}

export function homophoneTableRaw(): string {
  if (rawText === null) {
    try {
      rawText = readFileSync(resolvePath(), 'utf8');
    } catch (error) {
      // Without the table the context pass has nothing to verify against, so it
      // refuses everything — which is the safe direction, and loud.
      // eslint-disable-next-line no-console
      console.error('[quill] homophone table missing; context recovery is disabled', error);
      rawText = '';
    }
  }
  return rawText;
}

/// word -> every word that sounds like it, built once.
///
/// Unioned rather than assigned, because a word can have more than one
/// pronunciation and therefore appear in more than one group. "read" is in both
/// {read, reed} and {read, red}; assigning would leave it in whichever came
/// last and silently refuse the other swap.
///
/// Unioning keeps the relation symmetric without making it transitive: read
/// reaches both reed and red, while reed and red still cannot reach each other,
/// which is correct — they are not homophones.
export function homophoneGroupOf(): Map<string, Set<string>> {
  if (groups) return groups;
  groups = new Map();
  for (const line of homophoneTableRaw().split('\n')) {
    const group = line.split(' ').filter((word) => word.length > 0);
    if (group.length === 0) continue;
    for (const word of group) {
      let existing = groups.get(word);
      if (!existing) {
        existing = new Set();
        groups.set(word, existing);
      }
      for (const other of group) existing.add(other);
    }
  }
  return groups;
}
