#!/usr/bin/env python3
"""Generates Sources/QuillKit/Cleanup/HomophoneTable.swift from CMUdict.

Why this exists
---------------
The context pass lets the model propose a fix freely and then REFUSES the
proposal unless the replacement is a true homophone of the word that was heard.
That check needs to know what English actually sounds like, and no hand-written
list can cover it — the one in HomophonePairs has 21 groups because a human
typed them.

Why generated rather than fetched at runtime: the app is offline by design
except for the one model call, and a table that can fail to download is a
feature that works on some launches. It is checked in, and this script is how it
is rebuilt.

    curl -L -o cmudict.dict \\
      https://raw.githubusercontent.com/cmusphinx/cmudict/master/cmudict.dict
    python3 rig/tools/make_homophone_table.py cmudict.dict

What is filtered out, and why
-----------------------------
CMUdict is full of surname spellings — laurey/lauri/laurie/laury/lawrie/lawry/
loree/lorey/lori/lorie/lorrie/lorry/lory/lowrie is one set. Those are proper
nouns, they are VocabularyCorrector's job rather than this one, and keeping them
would let the model rewrite someone's name into a different spelling of it. So a
member is kept only if it appears as an ordinary lowercase word in the system
dictionary.

Stress markers are stripped before comparing. "record" the noun and "record" the
verb differ only in stress and are the same spelling anyway, so keeping stress
would split real pairs for no gain.
"""
import collections
import re
import sys
from pathlib import Path

STRESS = re.compile(r"\d")
VARIANT = re.compile(r"\(\d+\)$")
OUT = Path(__file__).resolve().parents[2] / "Sources/QuillKit/Cleanup/HomophoneTable.swift"
WORDS = Path("/usr/share/dict/words")


def main(dict_path):
    ordinary = set()
    if WORDS.exists():
        for line in WORDS.read_text(errors="ignore").splitlines():
            w = line.strip()
            if w.isalpha() and w.islower() and len(w) >= 2:
                ordinary.add(w)
    if not ordinary:
        sys.exit("no /usr/share/dict/words; cannot tell a word from a surname")

    prons = collections.defaultdict(set)
    for line in Path(dict_path).read_text(errors="ignore").splitlines():
        line = line.split("#")[0].strip()
        if not line:
            continue
        parts = line.split()
        word = VARIANT.sub("", parts[0]).lower()
        if not word.isalpha() or word not in ordinary:
            continue
        prons[word].add(" ".join(STRESS.sub("", p) for p in parts[1:]))

    by_sound = collections.defaultdict(set)
    for word, sounds in prons.items():
        for s in sounds:
            by_sound[s].add(word)

    groups = sorted(
        (sorted(v) for v in by_sound.values() if len(v) > 1),
        key=lambda g: g[0],
    )
    words = sorted({w for g in groups for w in g})

    # One line per group, words separated by spaces, groups by newline. Parsed
    # once on first use. A dictionary literal of 20k entries is minutes of
    # compile time; a string literal is instant.
    blob = "\n".join(" ".join(g) for g in groups)

    OUT.write_text(f'''// GENERATED by rig/tools/make_homophone_table.py — do not edit by hand.
//
// Every set of English words that CMUdict says are pronounced identically, with
// stress ignored, restricted to words the system dictionary lists as ordinary
// lowercase English. {len(groups)} sets, {len(words)} words.
//
// This is the CHECK, not the offer. The model proposes a fix freely and
// `ContextProjection` refuses it unless the replacement is in the same set as
// the word that was heard, so the blast radius is "words that sound the same"
// by construction rather than by inspection.
//
// Surname spellings are deliberately absent — laurie/lorry/lori and friends are
// proper nouns, they belong to VocabularyCorrector, and letting a model swap
// between them would rewrite someone's name into a different spelling of it.

import Foundation

enum HomophoneTable {{

    /// Groups, one per line, words separated by spaces. A string rather than a
    /// dictionary literal because a 20,000-entry literal costs minutes of
    /// compile time and this costs none.
    static let raw = """
{blob}
"""

    /// word -> every word that sounds like it, built once.
    ///
    /// Unioned rather than assigned, because a word can have more than one
    /// pronunciation and therefore appear in more than one group. "read" is in
    /// both {{read, reed}} and {{read, red}}; assigning would leave it in whichever
    /// came last and silently refuse the other swap.
    ///
    /// Unioning keeps the relation symmetric without making it transitive: read
    /// reaches both reed and red, while reed and red still cannot reach each
    /// other, which is correct — they are not homophones.
    static let groupOf: [String: Set<String>] = {{
        var out: [String: Set<String>] = [:]
        out.reserveCapacity({len(words)})
        for line in raw.split(separator: "\\n") {{
            let group = Set(line.split(separator: " ").map(String.init))
            for word in group {{ out[word, default: []].formUnion(group) }}
        }}
        return out
    }}()
}}
''')
    print(f"{len(groups)} groups, {len(words)} words -> {OUT}")
    print(f"blob is {len(blob)/1024:.0f} KB")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "cmudict.dict")
