// Does the recogniser tell us which word it was unsure about?
//
// Roman's ask is "if it can't really understand a word that I said, read the
// context and figure out what word makes the most sense". The existing homophone
// pass answers a narrower question — it can only choose between words on a
// hand-written list — and the reason it is a list at all is blast radius: a model
// asked to fix any wrong word will eventually rewrite one the user meant.
//
// But SpeechTranscriber.Result carries `alternatives`, and Quill has never asked
// for them. If they are populated and per-span, they are a better bound than any
// list: the candidate set is generated by the acoustic model for THIS utterance,
// it is exactly the set of things the recogniser itself considered, and a
// projection can enforce "the replacement must be one of these" in code.
//
// That would make the answer to "what word did I actually say" come from the
// recogniser, with the language model only choosing between candidates it already
// produced. So: are they populated, what shape are they, and do they contain the
// right answer when the top choice is wrong?
//
// Run: LiveTypeProbe --alternatives <audio.wav>

import AVFoundation
import Foundation
import QuillKit
import Speech

enum AlternativesProbe {

    static func run(url: URL) async {
        let locale = SpeechAssets.preferredLocale
        print("locale: \(locale.identifier(.bcp47))")

        // The one line Quill does not have today.
        let module = SpeechTranscriber(
            locale: locale,
            transcriptionOptions: [],
            reportingOptions: [.volatileResults, .alternativeTranscriptions],
            attributeOptions: [.audioTimeRange]
        )

        let analyzer = SpeechAnalyzer(modules: [module])
        guard let format = await SpeechAnalyzer.bestAvailableAudioFormat(compatibleWith: [module])
        else { print("no compatible format"); return }

        let (stream, continuation) = AsyncStream<AnalyzerInput>.makeStream()

        let drain = Task {
            var finals = 0
            do {
                for try await result in module.results {
                    let text = String(result.text.characters)
                    guard !result.alternatives.isEmpty || !text.isEmpty else { continue }
                    let isFinal = result.resultsFinalizationTime >= result.range.end
                    guard isFinal else { continue }
                    finals += 1
                    print("")
                    print("--- final span \(finals) ---")
                    print("  text          \(text)")
                    print("  alternatives  \(result.alternatives.count)")
                    for (i, alt) in result.alternatives.enumerated() {
                        print("     [\(i)] \(String(alt.characters))")
                    }
                    if result.alternatives.isEmpty {
                        print("     (none — the option did not populate them)")
                    }
                }
            } catch {
                print("drain error: \(error)")
            }
        }

        do {
            try await analyzer.start(inputSequence: stream)
        } catch {
            print("start failed: \(error)")
            return
        }

        // Feed the file as fast as it will take it; pacing does not change what
        // the alternatives contain.
        do {
            let file = try AVAudioFile(forReading: url)
            guard let converter = AVAudioConverter(from: file.processingFormat, to: format) else {
                print("no converter"); return
            }
            let frames: AVAudioFrameCount = 4096
            while true {
                guard let input = AVAudioPCMBuffer(pcmFormat: file.processingFormat,
                                                   frameCapacity: frames) else { break }
                try file.read(into: input, frameCount: frames)
                if input.frameLength == 0 { break }
                let ratio = format.sampleRate / file.processingFormat.sampleRate
                let capacity = AVAudioFrameCount(Double(input.frameLength) * ratio) + 1024
                guard let output = AVAudioPCMBuffer(pcmFormat: format, frameCapacity: capacity)
                else { break }
                var supplied = false
                var error: NSError?
                converter.convert(to: output, error: &error) {
                    _, status -> AVAudioBuffer? in
                    if supplied {
                        status.pointee = AVAudioConverterInputStatus.noDataNow
                        return nil
                    }
                    supplied = true
                    status.pointee = AVAudioConverterInputStatus.haveData
                    return input
                }
                if output.frameLength > 0 {
                    continuation.yield(AnalyzerInput(buffer: output))
                }
            }
        } catch {
            print("feed error: \(error)")
        }

        continuation.finish()
        try? await analyzer.finalizeAndFinishThroughEndOfInput()
        _ = await drain.value
        print("")
        print("done")
    }
}
